import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getZhibanPool } from '@/lib/zhiban/db/connection';
import { createOpenMaicActivityDocument, getTeacherOpenMaicActivityDocument, replaceOpenMaicActivityGeneratedDocument, replaceOpenMaicActivitySlides } from '@/lib/zhiban/openmaic-activity';
import type { Slide } from '@openmaic/dsl';
import type { Scene, Stage } from '@/lib/types/stage';
import { authorizationErrorResponse, requireRequestScopedPermission } from '@/lib/zhiban/rbac';

async function context(courseId: string) { const id = z.uuid().parse(courseId); return { id, principal: await requireRequestScopedPermission('course:manage', { courseIds: [id] }) }; }
export async function GET(request: NextRequest, { params }: { params: Promise<{ courseId: string }> }) { try { const { id, principal } = await context((await params).courseId); const activityId = z.uuid().parse(request.nextUrl.searchParams.get('activityId')); return NextResponse.json({ document: await getTeacherOpenMaicActivityDocument(getZhibanPool(), principal, id, activityId) }); } catch (error) { return authorizationErrorResponse(error) ?? NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to load activity document' }, { status: 400 }); } }
export async function POST(request: NextRequest, { params }: { params: Promise<{ courseId: string }> }) { try { const { id, principal } = await context((await params).courseId); const { activityId, activityKind, replace } = z.object({ activityId: z.uuid(), activityKind: z.enum(['slide','quiz','interactive','pbl','visualization3d']), replace: z.boolean().default(false) }).parse(await request.json()); return NextResponse.json(await createOpenMaicActivityDocument(getZhibanPool(), principal, id, activityId, activityKind, replace)); } catch (error) { return authorizationErrorResponse(error) ?? NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to create activity document' }, { status: 400 }); } }
export async function PUT(request: NextRequest, { params }: { params: Promise<{ courseId: string }> }) { try { const { id, principal } = await context((await params).courseId); const body = await request.json(); const base = z.object({ activityId: z.uuid(), source: z.enum(['pptx','ai']) }).parse(body); if (base.source === 'pptx') { const slides = z.array(z.object({ id: z.string().min(1), elements: z.array(z.unknown()), viewportSize: z.number(), viewportRatio: z.number(), theme: z.record(z.string(), z.unknown()) }).passthrough()).min(1).max(300).parse(body.slides) as unknown as Slide[]; return NextResponse.json(await replaceOpenMaicActivitySlides(getZhibanPool(), principal, id, base.activityId, slides, 'pptx')); } const stage = z.object({ id: z.string().min(1), name: z.string().min(1) }).passthrough().parse(body.stage) as unknown as Stage; const scenes = z.array(z.object({ id: z.string(), stageId: z.string(), type: z.string(), title: z.string(), order: z.number(), content: z.record(z.string(), z.unknown()) }).passthrough()).min(1).max(300).parse(body.scenes) as unknown as Scene[]; return NextResponse.json(await replaceOpenMaicActivityGeneratedDocument(getZhibanPool(), principal, id, base.activityId, stage, scenes)); } catch (error) { return authorizationErrorResponse(error) ?? NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to import slide activity' }, { status: 400 }); } }
