import {
  STATION_IDS,
  type KnowledgePointDefinition,
  type KnowledgeStationDefinition,
  type StationId,
} from './types';

export const KNOWLEDGE_POINT_IDS = [
  'K01',
  'K02',
  'K03',
  'K04',
  'K05',
  'K06',
  'K07',
  'K08',
  'K09',
  'K10',
  'K11',
  'K12',
  'K13',
  'K14',
  'K15',
] as const;

export const KNOWLEDGE_STATIONS: readonly KnowledgeStationDefinition[] = [
  {
    id: 'station-01-system',
    title: '系统认知',
    objective: '认识自动生产线组成，并建立感知—控制—执行整体图景。',
    estimatedMinutes: 12,
    knowledgePointIds: ['K01', 'K02', 'K03'],
    available: true,
  },
  {
    id: 'station-02-sensing',
    title: '感知探秘',
    objective: '机器怎样知道工件到了？理解位置、传感器输出与 PLC 输入的关系。',
    estimatedMinutes: 9,
    knowledgePointIds: ['K04', 'K05', 'K06', 'K07', 'K08'],
    available: true,
  },
  {
    id: 'station-03-control',
    title: '控制推演',
    objective: 'PLC怎样根据输入作出控制决定？理解输入、逻辑与输出的信号传递。',
    estimatedMinutes: 9,
    knowledgePointIds: ['K09', 'K10', 'K11', 'K12'],
    available: true,
  },
  {
    id: 'station-04-actuation',
    title: '执行探索',
    objective: '一个控制信号怎样变成机械动作？理解输出到执行机构的完整链路。',
    estimatedMinutes: 6,
    knowledgePointIds: ['K13', 'K14'],
    available: true,
  },
  {
    id: 'station-05-diagnosis',
    title: '诊断训练',
    objective: '你能沿着信号链找到故障吗？使用“察—查—测—断—验”定位故障层级。',
    estimatedMinutes: 7,
    knowledgePointIds: ['K15'],
    available: true,
  },
  {
    id: 'station-06-virtual-lab',
    title: '综合实训',
    objective: '进入现有旗舰 Virtual Lab，使用五步法完成综合诊断。',
    estimatedMinutes: 15,
    knowledgePointIds: [],
    available: true,
  },
  {
    id: 'station-07-assessment',
    title: '评价提升',
    objective: '我哪里会了，哪里还需要加强？查看六维画像、补救与再练增值。',
    estimatedMinutes: 8,
    knowledgePointIds: [],
    available: true,
  },
] as const;

export const KNOWLEDGE_POINTS: readonly KnowledgePointDefinition[] = [
  {
    id: 'K01',
    stationId: 'station-01-system',
    title: '自动生产线基本组成',
    description: '在可旋转的自动输送系统中识别 S1、S2、PLC、电机、输送带和气缸。',
    learningObjective: '能说出关键设备名称、所属层级、主要作用及输入输出。',
    interactionType: 'scene_identification',
    estimatedMinutes: 4,
    prerequisites: [],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K02',
    stationId: 'station-01-system',
    title: '感知—控制—执行三层结构',
    description: '把 S2、PLC 和推料气缸分别归入感知层、控制层和执行层。',
    learningObjective: '能根据设备主要职责判断其在系统链路中的层级。',
    interactionType: 'classification',
    estimatedMinutes: 4,
    prerequisites: ['K01'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K03',
    stationId: 'station-01-system',
    title: '物理流、信息流与控制流',
    description: '通过一次正常生产流程，观察工件移动、传感器信号和执行机构动作的先后关系。',
    learningObjective: '能用“感知 → 控制 → 执行”解释三种流如何协同。',
    interactionType: 'flow_sequence',
    estimatedMinutes: 4,
    prerequisites: ['K01', 'K02'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K04',
    stationId: 'station-02-sensing',
    title: '光电传感器基本工作原理',
    description: '拖动工件经过 S2 检测区域，观察检测状态、输出电压和 PLC I0.2 的实时联动。',
    learningObjective: '能说明工件进入检测区域后，S2 与 I0.2 的基本变化。',
    interactionType: 'sensor_simulation',
    estimatedMinutes: 2,
    prerequisites: ['K01'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K05',
    stationId: 'station-02-sensing',
    title: '工件位置与传感器输出关系',
    description: '先预测信号状态，再验证工件在检测区前、内、后的实际联动。',
    learningObjective: '能根据工件位置预测 S2 是否有有效输出。',
    interactionType: 'prediction',
    estimatedMinutes: 2,
    prerequisites: ['K04'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K06',
    stationId: 'station-02-sensing',
    title: '24V供电状态判断',
    description: '测量 S2 供电端并区分“供电正常”与“传感器完全正常”。',
    learningObjective: '能理解 24V 只说明供电回路基本正常。',
    interactionType: 'measurement',
    estimatedMinutes: 2,
    prerequisites: ['K04'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K07',
    stationId: 'station-02-sensing',
    title: '传感器输出信号判断',
    description: '对比正常输出和无输出知识推演模式，理解供电与输出是两项不同证据。',
    learningObjective: '能依据输出电压判断是否已形成有效传感器信号。',
    interactionType: 'measurement',
    estimatedMinutes: 2,
    prerequisites: ['K06'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K08',
    stationId: 'station-02-sensing',
    title: '传感器与PLC输入映射',
    description: '沿信号线双向查看 S2 与 PLC I0.2 的对应关系。',
    learningObjective: '能解释“工件到位”与“PLC已收到输入”之间的条件关系。',
    interactionType: 'signal_mapping',
    estimatedMinutes: 1,
    prerequisites: ['K04', 'K07'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
  {
    id: 'K09',
    stationId: 'station-03-control',
    title: 'PLC输入/输出基本概念',
    description: '在 PLC 面板中区分进入 PLC 的 I 输入与从 PLC 发出的 Q 输出。',
    learningObjective: '能说明 I 与 Q 的信号方向及其对应的现场含义。',
    interactionType: 'plc_simulation',
    estimatedMinutes: 2,
    prerequisites: ['K08'],
  },
  {
    id: 'K10',
    stationId: 'station-03-control',
    title: 'I/O与现场设备映射',
    description: '双向关联 S2 与 I0.2、推料控制与 Q0.1。',
    learningObjective: '能把现场设备映射到正确的 PLC 地址。',
    interactionType: 'signal_mapping',
    estimatedMinutes: 2,
    prerequisites: ['K09'],
  },
  {
    id: 'K11',
    stationId: 'station-03-control',
    title: 'PLC输入—程序—输出扫描逻辑',
    description: '按读取输入、执行逻辑、更新输出三个步骤推进一次 PLC 扫描。',
    learningObjective: '能说出 PLC 扫描的基本顺序。',
    interactionType: 'plc_simulation',
    estimatedMinutes: 2,
    prerequisites: ['K09'],
  },
  {
    id: 'K12',
    stationId: 'station-03-control',
    title: '简单梯形图信号传递',
    description: '观察 I0.2 触点导通与 Q0.1 线圈状态的同步关系。',
    learningObjective: '能依据输入触点状态推演简单输出结果。',
    interactionType: 'ladder_logic',
    estimatedMinutes: 2,
    prerequisites: ['K10', 'K11'],
  },
  {
    id: 'K13',
    stationId: 'station-04-actuation',
    title: 'PLC输出—气缸执行链',
    description: '沿 Q0.1、电磁阀、气路到气缸，理解控制信号如何变成推料动作。',
    learningObjective: '能说明执行链中每个节点的输入、作用和输出。',
    interactionType: 'execution_chain',
    estimatedMinutes: 3,
    prerequisites: ['K12'],
  },
  {
    id: 'K14',
    stationId: 'station-04-actuation',
    title: '控制信号与执行状态关系',
    description: '对比正常执行与执行失败推演，区分“有输出”和“动作成功”。',
    learningObjective: '能在 Q0.1 ON 但气缸不动时将范围缩小到执行侧。',
    interactionType: 'execution_chain',
    estimatedMinutes: 2,
    prerequisites: ['K13'],
  },
  {
    id: 'K15',
    stationId: 'station-05-diagnosis',
    title: '“察—查—测—断—验”循证诊断法',
    description: '依次观察现场、检查PLC、测量证据、判断层级并在维修后验证。',
    learningObjective: '能沿现场—输入—输出—执行链组织规范的故障诊断过程。',
    interactionType: 'signal_mapping',
    estimatedMinutes: 7,
    prerequisites: ['K08', 'K12', 'K14'],
    relatedActivityId: 'mech-lab-line-stop',
    relatedScenarioId: 'line-stop-001',
  },
] as const;

export function getStation(stationId: string): KnowledgeStationDefinition | null {
  return KNOWLEDGE_STATIONS.find((station) => station.id === stationId) ?? null;
}

export function getKnowledgePoint(knowledgePointId: string): KnowledgePointDefinition | null {
  return KNOWLEDGE_POINTS.find((point) => point.id === knowledgePointId) ?? null;
}

export function isStationId(value: string): value is StationId {
  return (STATION_IDS as readonly string[]).includes(value);
}
