import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getZhibanPool } from '@/lib/zhiban/db/connection';
import { recordOpenMaicActivityEvent, startOpenMaicActivitySession } from '@/lib/zhiban/openmaic-activity';
import { AuthorizationError, authorizationErrorResponse, requireRequestPrincipal } from '@/lib/zhiban/rbac';
const schema=z.object({courseId:z.uuid(),eventId:z.uuid(),eventType:z.string().min(1).max(40),sceneId:z.string().max(160).optional(),payload:z.record(z.string(),z.unknown()).default({}),occurredAt:z.iso.datetime()});
async function student(){const principal=await requireRequestPrincipal();if(!principal.permissions.includes('course:read'))throw new AuthorizationError('Permission denied');return principal;}
export async function POST(request:NextRequest,context:{params:Promise<{activityId:string}>}){try{const principal=await student(),{activityId}=await context.params,body=await request.json().catch(()=>null),courseId=typeof body?.courseId==='string'?body.courseId:'';if(!z.uuid().safeParse(courseId).success)return NextResponse.json({error:'Invalid course'},{status:400});return NextResponse.json(await startOpenMaicActivitySession(getZhibanPool(),principal,courseId,activityId));}catch(error){return authorizationErrorResponse(error)??NextResponse.json({error:error instanceof Error?error.message:'Unable to start activity'},{status:400});}}
export async function PATCH(request:NextRequest,context:{params:Promise<{activityId:string}>}){try{const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Invalid activity event'},{status:400});const principal=await student(),{activityId}=await context.params;return NextResponse.json(await recordOpenMaicActivityEvent(getZhibanPool(),principal,parsed.data.courseId,activityId,parsed.data));}catch(error){return authorizationErrorResponse(error)??NextResponse.json({error:error instanceof Error?error.message:'Unable to save activity event'},{status:400});}}
