import * as XLSX from 'xlsx';

const templates = {
  users: {
    headers: [
      '所属机构',
      '姓名',
      '登录名',
      '手机号',
      '邮箱',
      '证件类型',
      '证件号码',
      '身份',
      '状态',
      '创建时间',
    ],
    sample: [
      '3300804',
      '示例学生',
      '202600000001',
      '13800000000',
      'student@example.com',
      '居民身份证',
      '110101199606031234',
      '学生',
      '正常',
      '2026-08-12 09:00:00',
    ],
    notes: [
      ['填写说明'],
      ['所属机构填写机构固定代码或系统中的完整机构名称'],
      ['身份只能填写：学生、教师、管理员'],
      ['登录名全系统唯一；学生通常填写学号，教师通常填写工号'],
      ['证件号码和手机号请填写真实未脱敏数据'],
    ],
  },
  students: {
    headers: [
      '学号',
      '姓名',
      '入学年度学期',
      '学籍状态代码',
      '学籍状态',
      '学生类别代码',
      '学生类别',
      '分部代码',
      '分部',
      '学院代码',
      '学院',
      '学习中心代码',
      '学习中心',
      '班级代码',
      '班级名称',
      '班主任名称',
      '专业层次代码',
      '专业层次',
      '专业名称代码',
      '专业名称',
      '培养方案号',
    ],
    sample: [
      '202600000001',
      '示例学生',
      '2026春',
      '01',
      '在籍',
      '01',
      '开放教育',
      '330',
      '浙江分部',
      '33008',
      '台州开放大学',
      '3300804',
      '玉环学院',
      '2026JSJ01',
      '计算机应用基础一班',
      '示例教师',
      '1',
      '专科',
      '080901',
      '计算机科学与技术',
      'PY2026',
    ],
    notes: [
      ['填写说明'],
      ['请先导入用户数据，学号必须能关联到已存在的全局账号'],
      ['分部、学院、学习中心代码必须存在于系统机构树'],
    ],
  },
  registrations: {
    headers: [
      '学生入学学期',
      '选课年度学期',
      '学院名称',
      '学习中心名称',
      '学习中心代码',
      '专业层次',
      '专业',
      '学生类别',
      '学号',
      '姓名',
      '课程ID',
      '课程名称',
      '班主任工号',
      '班主任姓名',
      '班级名称',
      '学分',
      '学时',
      '考试单位',
      '课程类型',
      '课程性质',
      '建议开设学期',
      '修读类型',
      '选课次数',
      '注册时间',
      '注册操作人',
      '是否转报考',
      '选课状态',
      '是否确认',
      '确认时间',
      '确认操作人',
      '缴费状态',
      '备注',
    ],
    sample: [
      '2026春',
      '2026春',
      '台州开放大学',
      '玉环学院',
      '3300804',
      '专科',
      '计算机科学与技术',
      '开放教育',
      '202600000001',
      '示例学生',
      '00001',
      '计算机应用基础',
      'T00001',
      '示例教师',
      '计算机应用基础一班',
      '4',
      '72',
      '分部',
      '统设',
      '必修',
      '1',
      '正常',
      '1',
      '2026-03-01 09:00:00',
      'admin',
      '否',
      '已选课',
      '是',
      '2026-03-01 09:00:00',
      'admin',
      '已缴费',
      '',
    ],
    notes: [
      ['填写说明'],
      ['请先导入用户数据和学生数据'],
      ['课程ID、学号、学习中心代码为关键匹配字段'],
    ],
  },
} as const;

export type OucTemplateType = keyof typeof templates;

export function createOucImportTemplate(type: OucTemplateType) {
  const definition = templates[type];
  const workbook = XLSX.utils.book_new();
  const data = XLSX.utils.aoa_to_sheet([[...definition.headers], [...definition.sample]]);
  data['!cols'] = definition.headers.map((header) => ({
    wch: Math.max(14, header.length * 2 + 4),
  }));
  XLSX.utils.book_append_sheet(workbook, data, '导入数据');
  const notes = XLSX.utils.aoa_to_sheet(definition.notes.map((row) => [...row]));
  notes['!cols'] = [{ wch: 80 }];
  XLSX.utils.book_append_sheet(workbook, notes, '填写说明');
  return XLSX.write(workbook, { bookType: 'xlsx', type: 'buffer' }) as Buffer;
}
