import type { ZhibanMigration } from './001-initial-identity';

export const completeTeacherCourseSettingsMigration: ZhibanMigration = {
  version: '008',
  description: 'complete teacher configurable course policies',
  checksum: 'zhiban-008-complete-teacher-course-settings-v1',
  up: [
    `ALTER TABLE zhiban.course_settings
      ADD COLUMN starts_at TIMESTAMPTZ,
      ADD COLUMN ends_at TIMESTAMPTZ,
      ADD COLUMN pbl_projects JSONB NOT NULL DEFAULT '[]'::jsonb,
      ADD COLUMN scene_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
      ADD COLUMN course_resources JSONB NOT NULL DEFAULT '[]'::jsonb,
      ADD COLUMN prompt_strategy JSONB NOT NULL DEFAULT '{"version":"v1","policy":""}'::jsonb,
      ADD COLUMN grading_policy JSONB NOT NULL DEFAULT '{"formativeWeight":40,"projectWeight":30,"finalWeight":30}'::jsonb,
      ADD COLUMN assignment_policy JSONB NOT NULL DEFAULT '{"assignmentCount":0,"maxAttempts":1}'::jsonb,
      ADD COLUMN warning_policy JSONB NOT NULL DEFAULT '{"scoreThreshold":60,"inactivityDays":7,"missedAssignments":2}'::jsonb,
      ADD COLUMN intervention_policy JSONB NOT NULL DEFAULT '{"strategy":"notify_teacher","message":""}'::jsonb,
      ADD CONSTRAINT course_settings_date_order CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at),
      ADD CONSTRAINT course_settings_pbl_projects_array CHECK (jsonb_typeof(pbl_projects) = 'array'),
      ADD CONSTRAINT course_settings_scene_rules_array CHECK (jsonb_typeof(scene_rules) = 'array'),
      ADD CONSTRAINT course_settings_resources_array CHECK (jsonb_typeof(course_resources) = 'array'),
      ADD CONSTRAINT course_settings_prompt_strategy_object CHECK (jsonb_typeof(prompt_strategy) = 'object'),
      ADD CONSTRAINT course_settings_grading_policy_object CHECK (jsonb_typeof(grading_policy) = 'object'),
      ADD CONSTRAINT course_settings_assignment_policy_object CHECK (jsonb_typeof(assignment_policy) = 'object'),
      ADD CONSTRAINT course_settings_warning_policy_object CHECK (jsonb_typeof(warning_policy) = 'object'),
      ADD CONSTRAINT course_settings_intervention_policy_object CHECK (jsonb_typeof(intervention_policy) = 'object')`,
  ],
  down: [
    `ALTER TABLE zhiban.course_settings
      DROP CONSTRAINT IF EXISTS course_settings_intervention_policy_object,
      DROP CONSTRAINT IF EXISTS course_settings_warning_policy_object,
      DROP CONSTRAINT IF EXISTS course_settings_assignment_policy_object,
      DROP CONSTRAINT IF EXISTS course_settings_grading_policy_object,
      DROP CONSTRAINT IF EXISTS course_settings_prompt_strategy_object,
      DROP CONSTRAINT IF EXISTS course_settings_resources_array,
      DROP CONSTRAINT IF EXISTS course_settings_scene_rules_array,
      DROP CONSTRAINT IF EXISTS course_settings_pbl_projects_array,
      DROP CONSTRAINT IF EXISTS course_settings_date_order,
      DROP COLUMN IF EXISTS intervention_policy,
      DROP COLUMN IF EXISTS warning_policy,
      DROP COLUMN IF EXISTS assignment_policy,
      DROP COLUMN IF EXISTS grading_policy,
      DROP COLUMN IF EXISTS prompt_strategy,
      DROP COLUMN IF EXISTS course_resources,
      DROP COLUMN IF EXISTS scene_rules,
      DROP COLUMN IF EXISTS pbl_projects,
      DROP COLUMN IF EXISTS ends_at,
      DROP COLUMN IF EXISTS starts_at`,
  ],
};
