import type { ZhibanMigration } from './001-initial-identity';

const tenantSetting = `NULLIF(current_setting('zhiban.tenant_id', true), '')::uuid`;
const tables = ['pbl_projects', 'pbl_project_instances', 'pbl_learning_events', 'pbl_submissions', 'pbl_evaluations'];

export const pblLearningMigration: ZhibanMigration = {
  version: '009',
  description: 'PBL project definitions, learner instances, events, submissions, and evaluations',
  checksum: 'zhiban-009-pbl-learning-v1',
  up: [
    `CREATE TABLE zhiban.pbl_projects (
      id UUID PRIMARY KEY,
      tenant_id UUID NOT NULL,
      course_id UUID NOT NULL,
      code VARCHAR(80) NOT NULL,
      title VARCHAR(200) NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      learning_objective TEXT NOT NULL DEFAULT '',
      target_skills JSONB NOT NULL DEFAULT '[]'::jsonb,
      deliverable TEXT NOT NULL DEFAULT '',
      scenario_roleplay BOOLEAN NOT NULL DEFAULT false,
      scenario_brief TEXT NOT NULL DEFAULT '',
      opens_at TIMESTAMPTZ,
      closes_at TIMESTAMPTZ,
      status VARCHAR(24) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
      openmaic_package JSONB,
      package_version INTEGER NOT NULL DEFAULT 0 CHECK (package_version >= 0),
      created_by UUID NOT NULL,
      updated_by UUID NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (course_id, tenant_id) REFERENCES zhiban.courses(id, tenant_id) ON DELETE CASCADE,
      FOREIGN KEY (created_by, tenant_id) REFERENCES zhiban.accounts(id, tenant_id) ON DELETE RESTRICT,
      FOREIGN KEY (updated_by, tenant_id) REFERENCES zhiban.accounts(id, tenant_id) ON DELETE RESTRICT,
      UNIQUE (tenant_id, code), UNIQUE (id, tenant_id),
      CHECK (jsonb_typeof(target_skills) = 'array'),
      CHECK (openmaic_package IS NULL OR jsonb_typeof(openmaic_package) = 'object'),
      CHECK (closes_at IS NULL OR opens_at IS NULL OR closes_at >= opens_at)
    )`,
    `CREATE TABLE zhiban.pbl_project_instances (
      id UUID PRIMARY KEY,
      tenant_id UUID NOT NULL,
      project_id UUID NOT NULL,
      student_id UUID NOT NULL,
      package_version INTEGER NOT NULL CHECK (package_version > 0),
      project_state JSONB NOT NULL,
      status VARCHAR(24) NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started','in_progress','completed','withdrawn')),
      progress_percent NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (progress_percent BETWEEN 0 AND 100),
      started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      last_activity_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (project_id, tenant_id) REFERENCES zhiban.pbl_projects(id, tenant_id) ON DELETE CASCADE,
      FOREIGN KEY (student_id, tenant_id) REFERENCES zhiban.accounts(id, tenant_id) ON DELETE CASCADE,
      UNIQUE (project_id, student_id), UNIQUE (id, tenant_id),
      CHECK (jsonb_typeof(project_state) = 'object')
    )`,
    `CREATE TABLE zhiban.pbl_learning_events (
      id UUID PRIMARY KEY,
      tenant_id UUID NOT NULL,
      instance_id UUID NOT NULL,
      source_event_id VARCHAR(160),
      event_type VARCHAR(80) NOT NULL,
      actor_type VARCHAR(24) NOT NULL CHECK (actor_type IN ('student','teacher','agent','system')),
      payload JSONB NOT NULL DEFAULT '{}'::jsonb,
      occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (instance_id, tenant_id) REFERENCES zhiban.pbl_project_instances(id, tenant_id) ON DELETE CASCADE,
      UNIQUE (instance_id, source_event_id),
      CHECK (jsonb_typeof(payload) = 'object')
    )`,
    `CREATE TABLE zhiban.pbl_submissions (
      id UUID PRIMARY KEY,
      tenant_id UUID NOT NULL,
      instance_id UUID NOT NULL,
      milestone_id VARCHAR(160),
      microtask_id VARCHAR(160) NOT NULL,
      kind VARCHAR(24) NOT NULL CHECK (kind IN ('text','file','link')),
      content TEXT NOT NULL DEFAULT '',
      file_url TEXT,
      attempt INTEGER NOT NULL CHECK (attempt > 0),
      submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (instance_id, tenant_id) REFERENCES zhiban.pbl_project_instances(id, tenant_id) ON DELETE CASCADE,
      UNIQUE (instance_id, microtask_id, attempt), UNIQUE (id, tenant_id)
    )`,
    `CREATE TABLE zhiban.pbl_evaluations (
      id UUID PRIMARY KEY,
      tenant_id UUID NOT NULL,
      instance_id UUID NOT NULL,
      source_evaluation_id VARCHAR(160),
      kind VARCHAR(24) NOT NULL CHECK (kind IN ('task','milestone','final')),
      milestone_id VARCHAR(160),
      microtask_id VARCHAR(160),
      score NUMERIC(5,2) CHECK (score IS NULL OR score BETWEEN 0 AND 100),
      feedback TEXT NOT NULL DEFAULT '',
      evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
      evaluated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (instance_id, tenant_id) REFERENCES zhiban.pbl_project_instances(id, tenant_id) ON DELETE CASCADE,
      UNIQUE (instance_id, source_evaluation_id),
      CHECK (jsonb_typeof(evidence) = 'object')
    )`,
    ...tables.flatMap((table) => [
      `ALTER TABLE zhiban.${table} ENABLE ROW LEVEL SECURITY`,
      `ALTER TABLE zhiban.${table} FORCE ROW LEVEL SECURITY`,
      `CREATE POLICY tenant_isolation ON zhiban.${table} USING (tenant_id = ${tenantSetting}) WITH CHECK (tenant_id = ${tenantSetting})`,
    ]),
    `CREATE INDEX pbl_projects_course_idx ON zhiban.pbl_projects (tenant_id, course_id, status)`,
    `CREATE INDEX pbl_instances_student_idx ON zhiban.pbl_project_instances (tenant_id, student_id, status)`,
    `CREATE INDEX pbl_events_instance_time_idx ON zhiban.pbl_learning_events (instance_id, occurred_at)`,
  ],
  down: tables.slice().reverse().map((table) => `DROP TABLE IF EXISTS zhiban.${table}`),
};
