import type { ZhibanMigration } from './001-initial-identity';
const tenantSetting=`NULLIF(current_setting('zhiban.tenant_id',true),'')::uuid`;
export const gradeGovernanceMigration:ZhibanMigration={version:'022',description:'grade special states, review requests and publication batches',checksum:'zhiban-022-grade-governance-v1',up:[
 `ALTER TABLE zhiban.course_grade_records DROP CONSTRAINT course_grade_records_status_check`,
 `ALTER TABLE zhiban.course_grade_records ADD CONSTRAINT course_grade_records_status_check CHECK(status IN('draft','published','excused','absent','deferred','makeup','void'))`,
 `CREATE TABLE zhiban.grade_publication_batches(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,course_id UUID NOT NULL,publication_type VARCHAR(24) NOT NULL CHECK(publication_type IN('records','final_grades','withdrawal')),record_count INTEGER NOT NULL DEFAULT 0,actor_id UUID NOT NULL,reason TEXT NOT NULL DEFAULT '',snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),FOREIGN KEY(course_id,tenant_id) REFERENCES zhiban.courses(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(actor_id,tenant_id) REFERENCES zhiban.accounts(id,tenant_id),CHECK(jsonb_typeof(snapshot)='object'))`,
 `CREATE TABLE zhiban.grade_review_requests(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,course_id UUID NOT NULL,student_id UUID NOT NULL,grade_record_id UUID,final_grade_id UUID,reason TEXT NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'pending' CHECK(status IN('pending','approved','rejected','cancelled')),resolution TEXT NOT NULL DEFAULT '',handled_by UUID,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),handled_at TIMESTAMPTZ,FOREIGN KEY(course_id,tenant_id) REFERENCES zhiban.courses(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(student_id,tenant_id) REFERENCES zhiban.accounts(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(grade_record_id,tenant_id) REFERENCES zhiban.course_grade_records(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(final_grade_id,tenant_id) REFERENCES zhiban.course_final_grades(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(handled_by,tenant_id) REFERENCES zhiban.accounts(id,tenant_id),CHECK((grade_record_id IS NOT NULL)::int+(final_grade_id IS NOT NULL)::int=1))`,
 ...['grade_publication_batches','grade_review_requests'].flatMap(t=>[`ALTER TABLE zhiban.${t} ENABLE ROW LEVEL SECURITY`,`ALTER TABLE zhiban.${t} FORCE ROW LEVEL SECURITY`,`CREATE POLICY tenant_isolation ON zhiban.${t} USING(tenant_id=${tenantSetting}) WITH CHECK(tenant_id=${tenantSetting})`]),
 `CREATE INDEX grade_review_requests_course_status_idx ON zhiban.grade_review_requests(tenant_id,course_id,status,created_at)`,
],down:[`DROP TABLE IF EXISTS zhiban.grade_review_requests`,`DROP TABLE IF EXISTS zhiban.grade_publication_batches`,`ALTER TABLE zhiban.course_grade_records DROP CONSTRAINT course_grade_records_status_check`,`ALTER TABLE zhiban.course_grade_records ADD CONSTRAINT course_grade_records_status_check CHECK(status IN('draft','published','excused','void'))`]};
