import type { ZhibanMigration } from './001-initial-identity';

const tenantSetting = `NULLIF(current_setting('zhiban.tenant_id', true), '')::uuid`;

export const oucOrganizationIdentityMigration: ZhibanMigration = {
  version: '025',
  description:
    'OUC four-level organizations, global login identifiers, identity imports, and rollback history',
  checksum: 'zhiban-025-ouc-organization-identity-v1',
  up: [
    `CREATE TABLE zhiban.organization_units (
      id UUID PRIMARY KEY,
      external_id VARCHAR(32) NOT NULL UNIQUE,
      parent_id UUID REFERENCES zhiban.organization_units(id) ON DELETE RESTRICT,
      organization_level SMALLINT NOT NULL CHECK (organization_level BETWEEN 1 AND 4),
      organization_type VARCHAR(24) NOT NULL CHECK (organization_type IN ('headquarters','branch','college','learning_center')),
      name VARCHAR(200) NOT NULL,
      full_name VARCHAR(800) NOT NULL,
      path_external_ids TEXT[] NOT NULL,
      status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled','archived')),
      source_system VARCHAR(32) NOT NULL DEFAULT 'ouchn',
      source_version VARCHAR(128),
      row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
      valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),
      valid_to TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CHECK (cardinality(path_external_ids) = organization_level),
      CHECK ((organization_level = 1 AND parent_id IS NULL) OR (organization_level > 1 AND parent_id IS NOT NULL))
    )`,
    `INSERT INTO zhiban.organization_units (id,external_id,parent_id,organization_level,organization_type,name,full_name,path_external_ids) VALUES
      ('51161000-0000-4000-8000-000000000001','51161',NULL,1,'headquarters','国家开放大学','国家开放大学',ARRAY['51161']),
      ('33000000-0000-4000-8000-000000000002','330','51161000-0000-4000-8000-000000000001',2,'branch','浙江分部','国家开放大学/浙江分部',ARRAY['51161','330']),
      ('33008000-0000-4000-8000-000000000003','33008','33000000-0000-4000-8000-000000000002',3,'college','台州开放大学','国家开放大学/浙江分部/台州开放大学',ARRAY['51161','330','33008']),
      ('33008040-0000-4000-8000-000000000004','3300804','33008000-0000-4000-8000-000000000003',4,'learning_center','玉环学院','国家开放大学/浙江分部/台州开放大学/玉环学院',ARRAY['51161','330','33008','3300804'])`,
    `CREATE TABLE zhiban.tenant_organization_bindings (
      tenant_id UUID NOT NULL REFERENCES zhiban.tenants(id) ON DELETE CASCADE,
      organization_id UUID NOT NULL REFERENCES zhiban.organization_units(id) ON DELETE RESTRICT,
      is_primary BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (tenant_id,organization_id)
    )`,
    `ALTER TABLE zhiban.tenant_organization_bindings ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.tenant_organization_bindings FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.tenant_organization_bindings USING (tenant_id = ${tenantSetting}) WITH CHECK (tenant_id = ${tenantSetting})`,
    `ALTER TABLE zhiban.accounts ADD COLUMN primary_organization_id UUID REFERENCES zhiban.organization_units(id) ON DELETE RESTRICT`,
    `ALTER TABLE zhiban.accounts ADD COLUMN source_system VARCHAR(32)`,
    `ALTER TABLE zhiban.accounts ADD COLUMN source_external_id VARCHAR(128)`,
    `ALTER TABLE zhiban.accounts ADD COLUMN source_created_at TIMESTAMPTZ`,
    `ALTER TABLE zhiban.accounts ADD COLUMN mobile_verified_at TIMESTAMPTZ`,
    `ALTER TABLE zhiban.accounts ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0)`,
    `CREATE UNIQUE INDEX accounts_source_identity_uq ON zhiban.accounts(source_system,source_external_id) WHERE source_system IS NOT NULL AND source_external_id IS NOT NULL AND deleted_at IS NULL`,
    `CREATE TABLE zhiban.account_organization_memberships (
      id UUID PRIMARY KEY,tenant_id UUID NOT NULL,account_id UUID NOT NULL,organization_id UUID NOT NULL REFERENCES zhiban.organization_units(id) ON DELETE RESTRICT,
      membership_type VARCHAR(24) NOT NULL DEFAULT 'primary' CHECK (membership_type IN ('primary','secondary','managed')),
      status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
      valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),valid_to TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (account_id,tenant_id) REFERENCES zhiban.accounts(id,tenant_id) ON DELETE CASCADE,
      UNIQUE (account_id,organization_id,membership_type)
    )`,
    `ALTER TABLE zhiban.account_organization_memberships ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.account_organization_memberships FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.account_organization_memberships USING (tenant_id = ${tenantSetting}) WITH CHECK (tenant_id = ${tenantSetting})`,
    `CREATE TABLE zhiban.account_login_identifiers (
      id UUID PRIMARY KEY,account_id UUID NOT NULL,tenant_id UUID NOT NULL,
      identifier_type VARCHAR(24) NOT NULL CHECK (identifier_type IN ('mobile','student_no','employee_no','admin_account','login_name')),
      lookup_hash CHAR(64) NOT NULL UNIQUE,display_mask VARCHAR(128) NOT NULL,verified BOOLEAN NOT NULL DEFAULT false,
      source_system VARCHAR(32) NOT NULL DEFAULT 'local',status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked')),
      valid_from TIMESTAMPTZ NOT NULL DEFAULT now(),valid_to TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (account_id,tenant_id) REFERENCES zhiban.accounts(id,tenant_id) ON DELETE CASCADE,
      UNIQUE (account_id,identifier_type,lookup_hash)
    )`,
    `CREATE INDEX account_login_identifiers_account_idx ON zhiban.account_login_identifiers(account_id,status)`,
    `ALTER TABLE zhiban.student_profiles
      ADD COLUMN birth_date DATE,
      ADD COLUMN identity_document_type VARCHAR(32),
      ADD COLUMN identity_number_encrypted BYTEA,
      ADD COLUMN identity_number_lookup_hash CHAR(64),
      ADD COLUMN identity_number_last4 VARCHAR(4),
      ADD COLUMN admission_term VARCHAR(32),
      ADD COLUMN registry_status_code VARCHAR(16),
      ADD COLUMN student_category_code VARCHAR(16),
      ADD COLUMN student_category_name VARCHAR(100),
      ADD COLUMN branch_organization_id UUID REFERENCES zhiban.organization_units(id),
      ADD COLUMN college_organization_id UUID REFERENCES zhiban.organization_units(id),
      ADD COLUMN learning_center_organization_id UUID REFERENCES zhiban.organization_units(id),
      ADD COLUMN class_code VARCHAR(64),
      ADD COLUMN class_name VARCHAR(200),
      ADD COLUMN head_teacher_name VARCHAR(200),
      ADD COLUMN program_level_code VARCHAR(32),
      ADD COLUMN program_level_name VARCHAR(100),
      ADD COLUMN training_plan_no VARCHAR(64),
      ADD COLUMN source_row_hash CHAR(64),
      ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0)`,
    `CREATE UNIQUE INDEX student_identity_number_uq ON zhiban.student_profiles(identity_number_lookup_hash) WHERE identity_number_lookup_hash IS NOT NULL`,
    `ALTER TABLE zhiban.teacher_profiles
      ADD COLUMN birth_date DATE,
      ADD COLUMN identity_document_type VARCHAR(32),
      ADD COLUMN identity_number_encrypted BYTEA,
      ADD COLUMN identity_number_lookup_hash CHAR(64),
      ADD COLUMN identity_number_last4 VARCHAR(4),
      ADD COLUMN organization_id UUID REFERENCES zhiban.organization_units(id),
      ADD COLUMN source_row_hash CHAR(64),
      ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0)`,
    `CREATE UNIQUE INDEX teacher_identity_number_uq ON zhiban.teacher_profiles(identity_number_lookup_hash) WHERE identity_number_lookup_hash IS NOT NULL`,
    `ALTER TABLE zhiban.admin_profiles ADD COLUMN organization_id UUID REFERENCES zhiban.organization_units(id)`,
    `ALTER TABLE zhiban.admin_profiles ADD COLUMN organization_level SMALLINT CHECK (organization_level BETWEEN 1 AND 4)`,
    `ALTER TABLE zhiban.admin_profiles ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0)`,
    `ALTER TABLE zhiban.authorization_scopes DROP CONSTRAINT authorization_scopes_scope_type_check`,
    `ALTER TABLE zhiban.authorization_scopes ADD CONSTRAINT authorization_scopes_scope_type_check CHECK (scope_type IN ('organization','project_group','class','course'))`,
    `ALTER TABLE zhiban.role_scope_policies DROP CONSTRAINT role_scope_policies_scope_type_check`,
    `ALTER TABLE zhiban.role_scope_policies ADD CONSTRAINT role_scope_policies_scope_type_check CHECK (scope_type IN ('self','organization','project_group','class','course','tenant','system'))`,
    `ALTER TABLE zhiban.role_assignments DROP CONSTRAINT role_assignments_scope_type_check`,
    `ALTER TABLE zhiban.role_assignments ADD CONSTRAINT role_assignments_scope_type_check CHECK (scope_type IN ('self','organization','project_group','class','course','tenant','system'))`,
    `INSERT INTO zhiban.authorization_scopes(id,tenant_id,scope_type,code,name,external_ref,parent_scope_id,metadata)
      SELECT ou.id,b.tenant_id,'organization',ou.external_id,ou.name,ou.external_id,ou.parent_id,jsonb_build_object('level',ou.organization_level,'type',ou.organization_type)
      FROM zhiban.tenant_organization_bindings b JOIN zhiban.organization_units ou ON ou.id=b.organization_id ON CONFLICT DO NOTHING`,
    `INSERT INTO zhiban.role_scope_policies(role_id,scope_type) SELECT id,'organization' FROM zhiban.roles WHERE code IN ('teaching_admin','institution_admin','system_admin') ON CONFLICT DO NOTHING`,
    `CREATE OR REPLACE FUNCTION zhiban.validate_role_assignment_scope() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM zhiban.role_scope_policies p WHERE p.role_id=NEW.role_id AND p.scope_type=NEW.scope_type) THEN RAISE EXCEPTION 'scope type % is not allowed for role %',NEW.scope_type,NEW.role_id; END IF;
        IF NEW.scope_type IN ('organization','project_group','class','course') AND NOT EXISTS (SELECT 1 FROM zhiban.authorization_scopes s WHERE s.id=NEW.scope_id AND s.tenant_id=NEW.tenant_id AND s.scope_type=NEW.scope_type AND s.status='active') THEN RAISE EXCEPTION 'authorization scope is missing, archived, or has the wrong type'; END IF;
        RETURN NEW;
      END $$`,
    `CREATE TABLE zhiban.identity_import_batches (
      id UUID PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES zhiban.tenants(id) ON DELETE CASCADE,created_by UUID NOT NULL,
      users_file_name VARCHAR(255) NOT NULL,users_file_sha256 CHAR(64) NOT NULL,students_file_name VARCHAR(255),students_file_sha256 CHAR(64),
      default_organization_id UUID NOT NULL REFERENCES zhiban.organization_units(id),
      unmatched_account_policy VARCHAR(24) NOT NULL CHECK (unmatched_account_policy IN ('reject','teacher','administrator')),
      initial_password_policy VARCHAR(32) NOT NULL DEFAULT 'ouchn_birthdate' CHECK (initial_password_policy IN ('ouchn_birthdate','random_one_time')),
      status VARCHAR(24) NOT NULL CHECK (status IN ('uploaded','validated','invalid','confirmed','running','completed','failed','rolling_back','rolled_back','rollback_conflict')),
      total_rows INTEGER NOT NULL DEFAULT 0,valid_rows INTEGER NOT NULL DEFAULT 0,invalid_rows INTEGER NOT NULL DEFAULT 0,
      encrypted_payload JSONB NOT NULL DEFAULT '{}'::jsonb,summary JSONB NOT NULL DEFAULT '{}'::jsonb,error_message TEXT,
      confirmed_by UUID,confirmed_at TIMESTAMPTZ,executed_at TIMESTAMPTZ,rolled_back_by UUID,rolled_back_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY (created_by,tenant_id) REFERENCES zhiban.accounts(id,tenant_id),
      CHECK (jsonb_typeof(encrypted_payload)='object'),CHECK (jsonb_typeof(summary)='object')
    )`,
    `CREATE TABLE zhiban.identity_import_rows (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id UUID NOT NULL,batch_id UUID NOT NULL REFERENCES zhiban.identity_import_batches(id) ON DELETE CASCADE,
      source_file VARCHAR(16) NOT NULL CHECK (source_file IN ('users','students')),row_number INTEGER NOT NULL CHECK (row_number>=2),business_key VARCHAR(200),
      source_row_hash CHAR(64) NOT NULL,encrypted_source JSONB NOT NULL,status VARCHAR(24) NOT NULL CHECK (status IN ('valid','invalid','created','updated','skipped','rolled_back','conflict')),
      errors JSONB NOT NULL DEFAULT '[]'::jsonb,warnings JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE(batch_id,source_file,row_number),CHECK(jsonb_typeof(encrypted_source)='object'),CHECK(jsonb_typeof(errors)='array'),CHECK(jsonb_typeof(warnings)='array')
    )`,
    `CREATE TABLE zhiban.identity_import_changes (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id UUID NOT NULL,batch_id UUID NOT NULL REFERENCES zhiban.identity_import_batches(id) ON DELETE CASCADE,
      import_row_id BIGINT REFERENCES zhiban.identity_import_rows(id) ON DELETE SET NULL,entity_type VARCHAR(64) NOT NULL,entity_id VARCHAR(200) NOT NULL,
      operation VARCHAR(16) NOT NULL CHECK(operation IN ('insert','update','link')),before_data JSONB,after_data JSONB,
      before_version INTEGER,after_version INTEGER,dependency_order INTEGER NOT NULL DEFAULT 0,rolled_back_at TIMESTAMPTZ,rollback_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CHECK(before_data IS NULL OR jsonb_typeof(before_data)='object'),CHECK(after_data IS NULL OR jsonb_typeof(after_data)='object')
    )`,
    `CREATE TABLE zhiban.identity_entity_revisions (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id UUID NOT NULL,entity_type VARCHAR(64) NOT NULL,entity_id VARCHAR(200) NOT NULL,
      revision INTEGER NOT NULL,operation VARCHAR(24) NOT NULL,changed_by UUID,import_batch_id UUID REFERENCES zhiban.identity_import_batches(id) ON DELETE SET NULL,
      before_data JSONB,after_data JSONB,changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,entity_type,entity_id,revision)
    )`,
    `ALTER TABLE zhiban.identity_import_batches ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.identity_import_batches FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.identity_import_batches USING (tenant_id=${tenantSetting}) WITH CHECK (tenant_id=${tenantSetting})`,
    `ALTER TABLE zhiban.identity_import_rows ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.identity_import_rows FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.identity_import_rows USING (tenant_id=${tenantSetting}) WITH CHECK (tenant_id=${tenantSetting})`,
    `ALTER TABLE zhiban.identity_import_changes ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.identity_import_changes FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.identity_import_changes USING (tenant_id=${tenantSetting}) WITH CHECK (tenant_id=${tenantSetting})`,
    `ALTER TABLE zhiban.identity_entity_revisions ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.identity_entity_revisions FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.identity_entity_revisions USING (tenant_id=${tenantSetting}) WITH CHECK (tenant_id=${tenantSetting})`,
    `CREATE INDEX identity_import_batches_tenant_created_idx ON zhiban.identity_import_batches(tenant_id,created_at DESC)`,
    `CREATE INDEX identity_import_changes_batch_order_idx ON zhiban.identity_import_changes(batch_id,dependency_order DESC,id DESC)`,
    `CREATE INDEX identity_revisions_entity_idx ON zhiban.identity_entity_revisions(tenant_id,entity_type,entity_id,revision DESC)`,
  ],
  down: [
    `DROP TABLE IF EXISTS zhiban.identity_entity_revisions`,
    `DROP TABLE IF EXISTS zhiban.identity_import_changes`,
    `DROP TABLE IF EXISTS zhiban.identity_import_rows`,
    `DROP TABLE IF EXISTS zhiban.identity_import_batches`,
    `DELETE FROM zhiban.role_assignments WHERE scope_type='organization'`,
    `DELETE FROM zhiban.role_scope_policies WHERE scope_type='organization'`,
    `DELETE FROM zhiban.authorization_scopes WHERE scope_type='organization'`,
    `ALTER TABLE zhiban.role_assignments DROP CONSTRAINT role_assignments_scope_type_check`,
    `ALTER TABLE zhiban.role_assignments ADD CONSTRAINT role_assignments_scope_type_check CHECK (scope_type IN ('self','project_group','class','course','tenant','system'))`,
    `ALTER TABLE zhiban.role_scope_policies DROP CONSTRAINT role_scope_policies_scope_type_check`,
    `ALTER TABLE zhiban.role_scope_policies ADD CONSTRAINT role_scope_policies_scope_type_check CHECK (scope_type IN ('self','project_group','class','course','tenant','system'))`,
    `ALTER TABLE zhiban.authorization_scopes DROP CONSTRAINT authorization_scopes_scope_type_check`,
    `ALTER TABLE zhiban.authorization_scopes ADD CONSTRAINT authorization_scopes_scope_type_check CHECK (scope_type IN ('project_group','class','course'))`,
    `DROP INDEX IF EXISTS zhiban.teacher_identity_number_uq`,
    `ALTER TABLE zhiban.teacher_profiles DROP COLUMN row_version,DROP COLUMN source_row_hash,DROP COLUMN organization_id,DROP COLUMN identity_number_last4,DROP COLUMN identity_number_lookup_hash,DROP COLUMN identity_number_encrypted,DROP COLUMN identity_document_type,DROP COLUMN birth_date`,
    `DROP INDEX IF EXISTS zhiban.student_identity_number_uq`,
    `ALTER TABLE zhiban.student_profiles DROP COLUMN row_version,DROP COLUMN source_row_hash,DROP COLUMN training_plan_no,DROP COLUMN program_level_name,DROP COLUMN program_level_code,DROP COLUMN head_teacher_name,DROP COLUMN class_name,DROP COLUMN class_code,DROP COLUMN learning_center_organization_id,DROP COLUMN college_organization_id,DROP COLUMN branch_organization_id,DROP COLUMN student_category_name,DROP COLUMN student_category_code,DROP COLUMN registry_status_code,DROP COLUMN admission_term,DROP COLUMN identity_number_last4,DROP COLUMN identity_number_lookup_hash,DROP COLUMN identity_number_encrypted,DROP COLUMN identity_document_type,DROP COLUMN birth_date`,
    `ALTER TABLE zhiban.admin_profiles DROP COLUMN row_version,DROP COLUMN organization_level,DROP COLUMN organization_id`,
    `DROP TABLE IF EXISTS zhiban.account_login_identifiers`,
    `DROP TABLE IF EXISTS zhiban.account_organization_memberships`,
    `DROP INDEX IF EXISTS zhiban.accounts_source_identity_uq`,
    `ALTER TABLE zhiban.accounts DROP COLUMN row_version,DROP COLUMN mobile_verified_at,DROP COLUMN source_created_at,DROP COLUMN source_external_id,DROP COLUMN source_system,DROP COLUMN primary_organization_id`,
    `DROP TABLE IF EXISTS zhiban.tenant_organization_bindings`,
    `DROP TABLE IF EXISTS zhiban.organization_units`,
  ],
};
