import type { ZhibanMigration } from './001-initial-identity';

const tenantSetting = `NULLIF(current_setting('zhiban.tenant_id', true), '')::uuid`;

export const oucCourseRegistrationMigration: ZhibanMigration = {
  version: '026',
  description:
    'OUC programs, class and course source attributes, registration details, and academic import rollback',
  checksum: 'zhiban-026-ouc-course-registration-v1',
  up: [
    `CREATE TABLE zhiban.academic_programs (
      id UUID PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES zhiban.tenants(id) ON DELETE CASCADE,
      organization_id UUID NOT NULL REFERENCES zhiban.organization_units(id) ON DELETE RESTRICT,
      code VARCHAR(64),name VARCHAR(240) NOT NULL,program_level VARCHAR(100) NOT NULL,student_category VARCHAR(100),
      status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended','archived')),
      source_system VARCHAR(32) NOT NULL DEFAULT 'ouchn',source_row_hash CHAR(64),row_version INTEGER NOT NULL DEFAULT 1 CHECK(row_version>0),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE(tenant_id,organization_id,name,program_level,student_category),UNIQUE(id,tenant_id)
    )`,
    `ALTER TABLE zhiban.academic_programs ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.academic_programs FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.academic_programs USING(tenant_id=${tenantSetting}) WITH CHECK(tenant_id=${tenantSetting})`,
    `ALTER TABLE zhiban.classes
      ADD COLUMN organization_id UUID REFERENCES zhiban.organization_units(id) ON DELETE RESTRICT,
      ADD COLUMN program_id UUID,
      ADD COLUMN admission_term_code VARCHAR(32),
      ADD COLUMN source_system VARCHAR(32),
      ADD COLUMN source_external_id VARCHAR(128),
      ADD COLUMN source_row_hash CHAR(64),
      ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK(row_version>0),
      ADD CONSTRAINT classes_program_fk FOREIGN KEY(program_id,tenant_id) REFERENCES zhiban.academic_programs(id,tenant_id) ON DELETE RESTRICT`,
    `CREATE UNIQUE INDEX classes_source_identity_uq ON zhiban.classes(source_system,source_external_id) WHERE source_system IS NOT NULL AND source_external_id IS NOT NULL`,
    `ALTER TABLE zhiban.courses
      ADD COLUMN external_course_id VARCHAR(64),
      ADD COLUMN contact_hours NUMERIC(8,2) CHECK(contact_hours IS NULL OR contact_hours>=0),
      ADD COLUMN exam_unit VARCHAR(100),
      ADD COLUMN course_type VARCHAR(100),
      ADD COLUMN course_nature VARCHAR(100),
      ADD COLUMN suggested_term SMALLINT CHECK(suggested_term IS NULL OR suggested_term>0),
      ADD COLUMN source_system VARCHAR(32),
      ADD COLUMN source_row_hash CHAR(64),
      ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK(row_version>0)`,
    `CREATE UNIQUE INDEX courses_external_course_id_uq ON zhiban.courses(tenant_id,external_course_id) WHERE external_course_id IS NOT NULL`,
    `ALTER TABLE zhiban.course_offerings
      ADD COLUMN organization_id UUID REFERENCES zhiban.organization_units(id) ON DELETE RESTRICT,
      ADD COLUMN academic_year_term VARCHAR(32),
      ADD COLUMN source_system VARCHAR(32),
      ADD COLUMN source_external_id VARCHAR(160),
      ADD COLUMN source_row_hash CHAR(64),
      ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK(row_version>0)`,
    `CREATE UNIQUE INDEX course_offerings_source_identity_uq ON zhiban.course_offerings(tenant_id,source_system,source_external_id) WHERE source_system IS NOT NULL AND source_external_id IS NOT NULL`,
    `ALTER TABLE zhiban.enrollments
      ADD COLUMN study_type VARCHAR(64),
      ADD COLUMN selection_count INTEGER NOT NULL DEFAULT 1 CHECK(selection_count>0),
      ADD COLUMN registered_at TIMESTAMPTZ,
      ADD COLUMN registered_by_external VARCHAR(128),
      ADD COLUMN registered_by_account_id UUID,
      ADD COLUMN transfer_to_exam BOOLEAN NOT NULL DEFAULT false,
      ADD COLUMN source_status VARCHAR(64),
      ADD COLUMN confirmation_status VARCHAR(64),
      ADD COLUMN confirmed_at TIMESTAMPTZ,
      ADD COLUMN confirmed_by_external VARCHAR(128),
      ADD COLUMN confirmed_by_account_id UUID,
      ADD COLUMN payment_status VARCHAR(64),
      ADD COLUMN source_remark TEXT,
      ADD COLUMN source_system VARCHAR(32),
      ADD COLUMN source_external_id VARCHAR(200),
      ADD COLUMN source_row_hash CHAR(64),
      ADD COLUMN row_version INTEGER NOT NULL DEFAULT 1 CHECK(row_version>0),
      ADD CONSTRAINT enrollments_registered_by_fk FOREIGN KEY(registered_by_account_id) REFERENCES zhiban.accounts(id) ON DELETE SET NULL,
      ADD CONSTRAINT enrollments_confirmed_by_fk FOREIGN KEY(confirmed_by_account_id) REFERENCES zhiban.accounts(id) ON DELETE SET NULL`,
    `CREATE UNIQUE INDEX enrollments_source_identity_uq ON zhiban.enrollments(tenant_id,source_system,source_external_id) WHERE source_system IS NOT NULL AND source_external_id IS NOT NULL`,
    `CREATE TABLE zhiban.academic_import_batches (
      id UUID PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES zhiban.tenants(id) ON DELETE CASCADE,created_by UUID NOT NULL,
      import_type VARCHAR(32) NOT NULL CHECK(import_type IN ('course_registration')),
      file_name VARCHAR(255) NOT NULL,file_sha256 CHAR(64) NOT NULL,default_organization_id UUID REFERENCES zhiban.organization_units(id),
      mode VARCHAR(24) NOT NULL DEFAULT 'upsert' CHECK(mode IN ('skip','upsert')),
      status VARCHAR(24) NOT NULL CHECK(status IN ('uploaded','validated','invalid','confirmed','running','completed','failed','rolling_back','rolled_back','rollback_conflict')),
      total_rows INTEGER NOT NULL DEFAULT 0,valid_rows INTEGER NOT NULL DEFAULT 0,invalid_rows INTEGER NOT NULL DEFAULT 0,
      encrypted_payload JSONB NOT NULL DEFAULT '{}'::jsonb,summary JSONB NOT NULL DEFAULT '{}'::jsonb,error_message TEXT,
      confirmed_by UUID,confirmed_at TIMESTAMPTZ,executed_at TIMESTAMPTZ,rolled_back_by UUID,rolled_back_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      FOREIGN KEY(created_by,tenant_id) REFERENCES zhiban.accounts(id,tenant_id),
      CHECK(jsonb_typeof(encrypted_payload)='object'),CHECK(jsonb_typeof(summary)='object')
    )`,
    `CREATE TABLE zhiban.academic_import_rows (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id UUID NOT NULL,batch_id UUID NOT NULL REFERENCES zhiban.academic_import_batches(id) ON DELETE CASCADE,
      row_number INTEGER NOT NULL CHECK(row_number>=2),business_key VARCHAR(240),source_row_hash CHAR(64) NOT NULL,encrypted_source JSONB NOT NULL,
      status VARCHAR(24) NOT NULL CHECK(status IN ('valid','invalid','created','updated','skipped','rolled_back','conflict')),
      errors JSONB NOT NULL DEFAULT '[]'::jsonb,warnings JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE(batch_id,row_number),CHECK(jsonb_typeof(encrypted_source)='object'),CHECK(jsonb_typeof(errors)='array'),CHECK(jsonb_typeof(warnings)='array')
    )`,
    `CREATE TABLE zhiban.academic_import_changes (
      id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id UUID NOT NULL,batch_id UUID NOT NULL REFERENCES zhiban.academic_import_batches(id) ON DELETE CASCADE,
      import_row_id BIGINT REFERENCES zhiban.academic_import_rows(id) ON DELETE SET NULL,entity_type VARCHAR(64) NOT NULL,entity_id VARCHAR(200) NOT NULL,
      operation VARCHAR(16) NOT NULL CHECK(operation IN ('insert','update','link')),before_data JSONB,after_data JSONB,before_version INTEGER,after_version INTEGER,
      dependency_order INTEGER NOT NULL DEFAULT 0,rolled_back_at TIMESTAMPTZ,rollback_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CHECK(before_data IS NULL OR jsonb_typeof(before_data)='object'),CHECK(after_data IS NULL OR jsonb_typeof(after_data)='object')
    )`,
    `ALTER TABLE zhiban.academic_import_batches ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.academic_import_batches FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.academic_import_batches USING(tenant_id=${tenantSetting}) WITH CHECK(tenant_id=${tenantSetting})`,
    `ALTER TABLE zhiban.academic_import_rows ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.academic_import_rows FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.academic_import_rows USING(tenant_id=${tenantSetting}) WITH CHECK(tenant_id=${tenantSetting})`,
    `ALTER TABLE zhiban.academic_import_changes ENABLE ROW LEVEL SECURITY`,
    `ALTER TABLE zhiban.academic_import_changes FORCE ROW LEVEL SECURITY`,
    `CREATE POLICY tenant_isolation ON zhiban.academic_import_changes USING(tenant_id=${tenantSetting}) WITH CHECK(tenant_id=${tenantSetting})`,
    `CREATE INDEX academic_import_batches_tenant_created_idx ON zhiban.academic_import_batches(tenant_id,created_at DESC)`,
    `CREATE INDEX academic_import_changes_batch_order_idx ON zhiban.academic_import_changes(batch_id,dependency_order DESC,id DESC)`,
  ],
  down: [
    `DROP TABLE IF EXISTS zhiban.academic_import_changes`,
    `DROP TABLE IF EXISTS zhiban.academic_import_rows`,
    `DROP TABLE IF EXISTS zhiban.academic_import_batches`,
    `DROP INDEX IF EXISTS zhiban.enrollments_source_identity_uq`,
    `ALTER TABLE zhiban.enrollments DROP CONSTRAINT enrollments_confirmed_by_fk,DROP CONSTRAINT enrollments_registered_by_fk,DROP COLUMN row_version,DROP COLUMN source_row_hash,DROP COLUMN source_external_id,DROP COLUMN source_system,DROP COLUMN source_remark,DROP COLUMN payment_status,DROP COLUMN confirmed_by_account_id,DROP COLUMN confirmed_by_external,DROP COLUMN confirmed_at,DROP COLUMN confirmation_status,DROP COLUMN source_status,DROP COLUMN transfer_to_exam,DROP COLUMN registered_by_account_id,DROP COLUMN registered_by_external,DROP COLUMN registered_at,DROP COLUMN selection_count,DROP COLUMN study_type`,
    `DROP INDEX IF EXISTS zhiban.course_offerings_source_identity_uq`,
    `ALTER TABLE zhiban.course_offerings DROP COLUMN row_version,DROP COLUMN source_row_hash,DROP COLUMN source_external_id,DROP COLUMN source_system,DROP COLUMN academic_year_term,DROP COLUMN organization_id`,
    `DROP INDEX IF EXISTS zhiban.courses_external_course_id_uq`,
    `ALTER TABLE zhiban.courses DROP COLUMN row_version,DROP COLUMN source_row_hash,DROP COLUMN source_system,DROP COLUMN suggested_term,DROP COLUMN course_nature,DROP COLUMN course_type,DROP COLUMN exam_unit,DROP COLUMN contact_hours,DROP COLUMN external_course_id`,
    `DROP INDEX IF EXISTS zhiban.classes_source_identity_uq`,
    `ALTER TABLE zhiban.classes DROP CONSTRAINT classes_program_fk,DROP COLUMN row_version,DROP COLUMN source_row_hash,DROP COLUMN source_external_id,DROP COLUMN source_system,DROP COLUMN admission_term_code,DROP COLUMN program_id,DROP COLUMN organization_id`,
    `DROP TABLE IF EXISTS zhiban.academic_programs`,
  ],
};
