import type { ZhibanMigration } from './001-initial-identity';
const tenant = `NULLIF(current_setting('zhiban.tenant_id',true),'')::uuid`;
export const independentOpenMaicActivitiesMigration: ZhibanMigration = {
  version: '042', description: 'independent OpenMAIC activity documents, sessions, and events', checksum: 'zhiban-042-independent-openmaic-activities-v1',
  up: [
    `CREATE TABLE zhiban.openmaic_activity_documents(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,course_id UUID NOT NULL,activity_id UUID NOT NULL,document_id VARCHAR(160) NOT NULL,stage JSONB NOT NULL,scenes JSONB NOT NULL,document_state JSONB NOT NULL DEFAULT '{}'::jsonb,revision BIGINT NOT NULL DEFAULT 1,status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK(status IN('draft','published','archived')),created_by UUID NOT NULL,updated_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,activity_id),UNIQUE(document_id),UNIQUE(id,tenant_id),FOREIGN KEY(course_id,tenant_id) REFERENCES zhiban.courses(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(activity_id,tenant_id) REFERENCES zhiban.course_activities(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(created_by,tenant_id) REFERENCES zhiban.accounts(id,tenant_id),FOREIGN KEY(updated_by,tenant_id) REFERENCES zhiban.accounts(id,tenant_id),CHECK(jsonb_typeof(stage)='object'),CHECK(jsonb_typeof(scenes)='array'),CHECK(jsonb_typeof(document_state)='object'))`,
    `CREATE TABLE zhiban.openmaic_activity_sessions(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,course_id UUID NOT NULL,activity_id UUID NOT NULL,student_id UUID NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'in_progress' CHECK(status IN('in_progress','completed')),attempt_count INTEGER NOT NULL DEFAULT 0,current_scene_id VARCHAR(160),state JSONB NOT NULL DEFAULT '{}'::jsonb,started_at TIMESTAMPTZ NOT NULL DEFAULT now(),last_activity_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ,UNIQUE(tenant_id,activity_id,student_id),UNIQUE(id,tenant_id),FOREIGN KEY(course_id,tenant_id) REFERENCES zhiban.courses(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(activity_id,tenant_id) REFERENCES zhiban.course_activities(id,tenant_id) ON DELETE CASCADE,FOREIGN KEY(student_id,tenant_id) REFERENCES zhiban.accounts(id,tenant_id) ON DELETE CASCADE,CHECK(jsonb_typeof(state)='object'))`,
    `CREATE TABLE zhiban.openmaic_activity_events(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,session_id UUID NOT NULL,event_id UUID NOT NULL,event_type VARCHAR(40) NOT NULL,scene_id VARCHAR(160),payload JSONB NOT NULL DEFAULT '{}'::jsonb,occurred_at TIMESTAMPTZ NOT NULL,received_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,event_id),UNIQUE(id,tenant_id),FOREIGN KEY(session_id,tenant_id) REFERENCES zhiban.openmaic_activity_sessions(id,tenant_id) ON DELETE CASCADE,CHECK(jsonb_typeof(payload)='object'))`,
    ...['openmaic_activity_documents','openmaic_activity_sessions','openmaic_activity_events'].flatMap((table)=>[`ALTER TABLE zhiban.${table} ENABLE ROW LEVEL SECURITY`,`ALTER TABLE zhiban.${table} FORCE ROW LEVEL SECURITY`,`CREATE POLICY tenant_isolation ON zhiban.${table} USING(tenant_id=${tenant}) WITH CHECK(tenant_id=${tenant})`]),
  ],
  down: [`DROP TABLE IF EXISTS zhiban.openmaic_activity_events`,`DROP TABLE IF EXISTS zhiban.openmaic_activity_sessions`,`DROP TABLE IF EXISTS zhiban.openmaic_activity_documents`],
};
