'use client';
import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

type Row = Record<string, unknown>;
interface Overview { project: { title: string; rubricId?: string | null; gradeItemId?: string | null }; tasks: Row[]; groups: Row[]; submissions: Row[]; students: Row[]; rubrics: Row[]; gradeItems: Row[] }
const selectClass = 'h-9 rounded-md border bg-transparent px-2 text-sm';
async function call(projectId: string, body?: unknown) { const response = await fetch(`/api/zhiban/pbl/projects/${projectId}/collaboration`, body ? { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) } : undefined); const value = await response.json(); if (!response.ok) throw new Error(value.error ?? '操作失败'); return value; }

export function PblCollaborationConsole({ projectId, onClose }: { projectId: string; onClose: () => void }) {
  const [data, setData] = useState<Overview | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setData(await call(projectId)); } catch (e) { toast.error(e instanceof Error ? e.message : '加载失败'); } }, [projectId]);
  useEffect(() => { void load(); }, [load]);
  async function action(body: unknown, success: string) { setBusy(true); try { await call(projectId, body); toast.success(success); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : '操作失败'); } finally { setBusy(false); } }
  if (!data) return <Card><CardContent className="p-6">正在加载协作设置…</CardContent></Card>;
  return <Card className="mt-6 border-teal-500"><CardHeader><CardTitle className="flex justify-between">协作与评价：{data.project.title}<Button variant="outline" onClick={onClose}>关闭</Button></CardTitle></CardHeader><CardContent className="space-y-8">
    <Section title="任务范围与依赖"><div className="space-y-3">{data.tasks.map((task) => <form key={String(task.id)} className="grid gap-2 rounded-md border p-3 md:grid-cols-[1fr_130px_1fr_auto]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: 'task_policy', taskId: task.id, taskScope: form.get('scope'), dependencies: form.getAll('dependencies') }, '任务策略已保存'); }}><div><b>{String(task.title)}</b><p className="text-xs text-slate-500">顺序 {String(Number(task.display_order) + 1)}</p></div><select name="scope" className={selectClass} defaultValue={String(task.task_scope)}><option value="individual">个人任务</option><option value="group">小组任务</option></select><select name="dependencies" multiple className="min-h-20 rounded-md border p-2 text-xs" defaultValue={Array.isArray(task.dependencies) ? task.dependencies.map(String) : []}>{data.tasks.filter((candidate) => candidate.id !== task.id).map((candidate) => <option key={String(candidate.id)} value={String(candidate.id)}>{String(candidate.title)}</option>)}</select><Button size="sm" disabled={busy}>保存</Button></form>)}</div></Section>
    <Section title="教师分组"><form className="grid gap-3 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: 'group', method: form.get('method'), groupSize: Number(form.get('groupSize')), studentIds: form.getAll('studentIds') }, '分组已生成'); }}><select name="method" className={selectClass}><option value="random">随机分组</option><option value="class">按班级顺序</option><option value="balanced">规则均衡分组</option><option value="manual">手工选择一组</option></select><Input name="groupSize" type="number" min={2} max={20} defaultValue={4} /><select name="studentIds" multiple className="min-h-24 rounded-md border p-2 text-xs">{data.students.map((student) => <option key={String(student.id)} value={String(student.id)}>{String(student.display_name)}</option>)}</select><Button disabled={busy}>执行分组</Button></form><div className="mt-4 grid gap-3 md:grid-cols-2">{data.groups.map((group) => <div key={String(group.id)} className="rounded-md border p-3"><b>{String(group.name)}</b><div className="mt-2 space-y-2">{(group.members as Row[]).map((member) => <div key={String(member.id)} className="flex items-center justify-between text-sm"><span>{String(member.name)}</span><select className={selectClass} value={String(member.role)} onChange={(event) => void action({ action: 'group_role', memberId: member.id, role: event.target.value }, '组内角色已更新')}><option value="leader">组长</option><option value="member">成员</option><option value="recorder">记录员</option><option value="presenter">汇报人</option></select></div>)}</div></div>)}</div></Section>
    <Section title="成果提交与教师审核"><div className="space-y-3">{data.submissions.map((submission) => <div key={String(submission.id)} className="rounded-md border p-3"><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: 'review', submissionId: submission.id, status: form.get('status'), feedback: form.get('feedback') }, '教师反馈已保存'); }}><div className="flex justify-between"><b>{String(submission.submitter_name)} · 版本 {String(submission.attempt)}</b><span className="text-xs">{String(submission.review_status)} · SHA-256 {String(submission.content_hash).slice(0, 12)}…</span></div><p className="my-2 whitespace-pre-wrap text-sm">{String(submission.content)}</p><div className="flex gap-2"><select name="status" className={selectClass} defaultValue={String(submission.review_status === 'approved' ? 'approved' : 'changes_requested')}><option value="changes_requested">退回修改</option><option value="approved">审核通过</option></select><Input name="feedback" defaultValue={String(submission.teacher_feedback ?? '')} placeholder="教师反馈" /><Button size="sm" disabled={busy}>提交审核</Button></div></form>{data.project.rubricId && <RubricScoring submission={submission} rubric={data.rubrics.find((rubric) => rubric.id === data.project.rubricId)} busy={busy} onScore={(body) => action(body, '量规评分已计入课程成绩项目')} />}</div>)}{!data.submissions.length && <p className="text-sm text-slate-500">暂无成果提交。</p>}</div></Section>
    <Section title="评分量规与课程成绩项"><form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const criteria = String(form.get('criteria')).split('\n').map((line) => line.trim()).filter(Boolean).map((line) => { const [code,name,weight,maxScore,description=''] = line.split('|').map((x) => x.trim()); return { code,name,weight:Number(weight),maxScore:Number(maxScore),description }; }); void action({ action: 'rubric', name: form.get('name'), description: form.get('description'), gradeItemCode: form.get('gradeItemCode'), gradeItemName: form.get('gradeItemName'), gradeWeight: Number(form.get('gradeWeight')), criteria }, '量规和成绩项已关联'); }}><Field label="量规名称"><Input name="name" required /></Field><Field label="量规说明"><Input name="description" /></Field><Field label="成绩项编码"><Input name="gradeItemCode" required /></Field><Field label="成绩项名称"><Input name="gradeItemName" required /></Field><Field label="课程项目成绩权重"><Input name="gradeWeight" type="number" min={0} max={100} defaultValue={30} required /></Field><div /><div className="md:col-span-2"><Field label="量规指标（每行：编码 | 名称 | 权重 | 满分 | 说明；权重合计100）"><Textarea name="criteria" rows={5} required /></Field></div><Button disabled={busy}>创建并关联</Button></form></Section>
    <Section title="项目模板"><form className="flex gap-3" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void action({ action: 'template', code: form.get('code'), name: form.get('name') }, '项目模板已发布'); }}><Input name="code" placeholder="模板编码" required /><Input name="name" placeholder="模板名称" required /><Button disabled={busy}>保存为模板</Button></form></Section>
  </CardContent></Card>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="mb-3 border-b pb-2 text-lg font-semibold">{title}</h3>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function RubricScoring({ submission, rubric, busy, onScore }: { submission: Row; rubric?: Row; busy: boolean; onScore: (body: unknown) => void }) {
  const criteria = Array.isArray(rubric?.criteria) ? rubric.criteria as Row[] : [];
  if (!criteria.length) return null;
  return <form className="mt-4 rounded-md bg-slate-50 p-3 dark:bg-slate-900" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const scores = criteria.map((criterion) => ({ criterionId: criterion.id, score: Number(form.get(`score:${criterion.id}`)), feedback: String(form.get(`feedback:${criterion.id}`) ?? '') })); onScore({ action: 'rubric_score', submissionId: submission.id, feedback: form.get('overallFeedback'), scores }); }}><b className="text-sm">量规评分（评分后自动审核通过并关联成绩项）</b><div className="mt-2 space-y-2">{criteria.map((criterion) => <div key={String(criterion.id)} className="grid gap-2 md:grid-cols-[1fr_120px_2fr]"><Label>{String(criterion.name)}（满分 {String(criterion.maxScore)}）</Label><Input name={`score:${criterion.id}`} type="number" min={0} max={Number(criterion.maxScore)} step="0.01" required /><Input name={`feedback:${criterion.id}`} placeholder="指标反馈" /></div>)}</div><div className="mt-2 flex gap-2"><Input name="overallFeedback" placeholder="综合评价" /><Button size="sm" disabled={busy}>提交评分</Button></div></form>;
}
