'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { CourseTutorConfig } from '@/lib/zhiban/tutor';

type Dashboard = { config: CourseTutorConfig; documents: Array<{ id: string; source_type: string; title: string; status: string; chunk_count: number; synced_at: string }>; usage: { session_count?: number; answer_count?: number; failure_count?: number; blocked_count?: number; average_latency_ms?: number; positive_feedback_percent?: number }; issues: Array<{ id: string; content: string; status: string; safety_category?: string; student_name: string; rating?: number; comment?: string; created_at: string }>; syncRuns: Array<{ id: string; trigger_type: string; status: string; source_count: number; changed_count: number; error_message?: string; started_at: string }> };

export function TeacherCourseTutor({ courseId }: { courseId: string }) {
  const [data, setData] = useState<Dashboard | null>(null), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/zhiban/teacher/courses/${courseId}/tutor`), body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'Tutor 配置加载失败'); setData(body); }, [courseId]);
  useEffect(() => { void load().catch((error) => toast.error(error.message)); }, [load]);
  const post = async (payload: Record<string, unknown>, message: string) => { setBusy(true); try { const response = await fetch(`/api/zhiban/teacher/courses/${courseId}/tutor`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }), body = await response.json(); if (!response.ok) throw new Error(body.error ?? '操作失败'); toast.success(message); await load(); } finally { setBusy(false); } };
  if (!data) return <section className="border bg-white p-5 text-sm text-slate-500">正在加载课程 Tutor……</section>;
  const config = data.config;
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void post({ enabled: form.get('enabled') === 'on', autoSync: form.get('autoSync') === 'on', displayName: form.get('displayName'), welcomeMessage: form.get('welcomeMessage'), systemPrompt: form.get('systemPrompt'), retrievalTopK: Number(form.get('retrievalTopK')), citationRequired: form.get('citationRequired') === 'on', answerScope: form.get('answerScope'), maxHistoryMessages: Number(form.get('maxHistoryMessages')), status: form.get('status') }, '课程 Tutor 配置已保存').catch((error) => toast.error(error.message)); };
  return <section className="space-y-5 border bg-white p-5">
    <div className="flex flex-wrap items-center gap-3"><div><h2 className="text-lg font-semibold">课程级 Tutor</h2><p className="text-sm text-slate-500">复用 OpenMAIC Tutor 人设与模型调用，回答范围由本课程知识库约束</p></div><div className="ml-auto grid grid-cols-3 gap-x-4 gap-y-1 text-xs text-slate-600"><span>会话 {data.usage.session_count ?? 0}</span><span>回答 {data.usage.answer_count ?? 0}</span><span>拦截 {data.usage.blocked_count ?? 0}</span><span>失败 {data.usage.failure_count ?? 0}</span><span>平均响应 {data.usage.average_latency_ms ?? 0}ms</span><span>好评 {data.usage.positive_feedback_percent ?? 0}%</span></div></div>
    <form onSubmit={save} className="grid gap-3 rounded border p-4 md:grid-cols-3">
      <label className="text-sm">显示名称<Input name="displayName" defaultValue={config.displayName} required /></label>
      <label className="text-sm">检索片段数<Input name="retrievalTopK" type="number" min="1" max="12" defaultValue={config.retrievalTopK} /></label>
      <label className="text-sm">历史消息数<Input name="maxHistoryMessages" type="number" min="2" max="40" defaultValue={config.maxHistoryMessages} /></label>
      <label className="text-sm md:col-span-3">欢迎语<textarea name="welcomeMessage" defaultValue={config.welcomeMessage} className="mt-1 min-h-20 w-full rounded border p-3" /></label>
      <label className="text-sm md:col-span-3">课程补充提示词<textarea name="systemPrompt" defaultValue={config.systemPrompt} className="mt-1 min-h-28 w-full rounded border p-3" placeholder="课程术语、教学方法、回答边界等" /></label>
      <select name="answerScope" defaultValue={config.answerScope} className="h-10 rounded border px-3 text-sm"><option value="course_only">仅依据课程资料</option><option value="course_first">课程资料优先，可补充通用知识</option></select>
      <select name="status" defaultValue={config.status} className="h-10 rounded border px-3 text-sm"><option value="draft">草稿</option><option value="published">发布给学生</option><option value="disabled">停用</option></select>
      <div className="flex flex-wrap items-center gap-4 text-sm"><label><input name="enabled" type="checkbox" defaultChecked={config.enabled} /> 启用</label><label><input name="autoSync" type="checkbox" defaultChecked={config.autoSync} /> 内容变更自动同步</label><label><input name="citationRequired" type="checkbox" defaultChecked={config.citationRequired} /> 强制引用来源</label></div>
      <Button disabled={busy}>保存 Tutor 配置</Button>
    </form>
    <div className="grid gap-4 lg:grid-cols-2"><div className="rounded border p-4"><div className="mb-3 flex items-center"><h3 className="font-semibold">课程知识库</h3><Button size="sm" variant="outline" className="ml-auto" disabled={busy} onClick={() => void post({ action: 'sync' }, '课程知识已同步').catch((error) => toast.error(error.message))}><RefreshCw className="mr-1 size-4" />同步课程内容</Button></div><p className="mb-3 text-xs text-slate-500">同步已发布章节内容、标记为 Tutor 知识库的资源及已发布作业要求。</p><div className="max-h-80 divide-y overflow-y-auto">{data.documents.map((document) => <div key={document.id} className="py-2 text-sm"><b>{document.title}</b><p className="text-xs text-slate-500">{document.source_type} · {document.chunk_count} 个片段 · {document.status}</p></div>)}{!data.documents.length && <p className="py-5 text-center text-sm text-slate-400">尚未同步知识资料。</p>}</div></div>
      <form className="rounded border p-4" onSubmit={(event) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); void post({ action: 'manual_document', title: form.get('title'), content: form.get('content') }, '补充资料已加入知识库').then(() => formElement.reset()).catch((error) => toast.error(error.message)); }}><h3 className="mb-3 font-semibold">添加教师补充资料</h3><Input name="title" required placeholder="资料标题" /><textarea name="content" required className="mt-3 min-h-52 w-full rounded border p-3 text-sm" placeholder="课程术语解释、常见误区、教学提示等" /><Button className="mt-3" disabled={busy}>加入知识库</Button><p className="mt-3 text-xs text-slate-500">同步状态：{config.lastSyncStatus} · 最近同步：{config.lastSyncedAt ? new Date(config.lastSyncedAt).toLocaleString() : '尚未同步'}{config.lastSyncError ? ` · ${config.lastSyncError}` : ''}</p></form></div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="rounded border p-4"><h3 className="mb-3 font-semibold">需要教师关注的回答</h3>{data.issues.length ? <div className="max-h-64 divide-y overflow-y-auto">{data.issues.map((issue) => <div key={issue.id} className="py-2 text-sm"><p className="line-clamp-2">{issue.content}</p><p className="mt-1 text-xs text-slate-500">{issue.student_name} · {issue.status}{issue.safety_category ? ` · ${issue.safety_category}` : ''}{issue.comment ? ` · ${issue.comment}` : ''}</p></div>)}</div> : <p className="text-sm text-slate-400">暂无失败、拦截或负面反馈。</p>}</div><div className="rounded border p-4"><h3 className="mb-3 font-semibold">知识同步记录</h3>{data.syncRuns.length ? <div className="max-h-64 divide-y overflow-y-auto">{data.syncRuns.map((run) => <div key={run.id} className="py-2 text-sm"><p>{run.trigger_type === 'automatic' ? '自动同步' : '手动同步'} · {run.status}</p><p className="text-xs text-slate-500">来源 {run.source_count} · 变更 {run.changed_count} · {new Date(run.started_at).toLocaleString()}{run.error_message ? ` · ${run.error_message}` : ''}</p></div>)}</div> : <p className="text-sm text-slate-400">暂无同步记录。</p>}</div></div>
  </section>;
}
