import { aiModeForStation } from '@/lib/zhiban/learning-center/diagnosis';
import type { ConceptErrorCode, StationId } from '@/lib/zhiban/learning-center/types';
import { MECH_LAB_ACTIVITY_ID } from '@/lib/zhiban/virtual-lab/registry';
import type {
  OpenMaicCapability,
  SceneCompletionRule,
  SceneDefinition,
  SceneId,
  SceneReuseStrategy,
  SceneType,
} from './types';

const SCENARIO_ID = 'line-stop-001';

function scene(input: {
  id: SceneId;
  stationId: StationId;
  title: string;
  description: string;
  sceneType: SceneType;
  reuseStrategy: SceneReuseStrategy;
  capabilities: OpenMaicCapability[];
  learningMode: SceneDefinition['learningMode'];
  prerequisite?: SceneId;
  completionRule: SceneCompletionRule;
  remediationFor?: ConceptErrorCode[];
  componentKey?: string;
  interactiveTemplate?: string;
  activity?: boolean;
  metadata?: Record<string, unknown>;
}): SceneDefinition {
  return {
    id: input.id,
    stationId: input.stationId,
    title: input.title,
    description: input.description,
    sceneType: input.sceneType,
    reuseStrategy: input.reuseStrategy,
    openmaicCapabilities: input.capabilities,
    learningMode: input.learningMode,
    aiMode: aiModeForStation(input.stationId),
    prerequisites: input.prerequisite ? [input.prerequisite] : [],
    completionRule: input.completionRule,
    remediationFor: input.remediationFor ?? [],
    componentKey: input.componentKey,
    interactiveTemplate: input.interactiveTemplate,
    ...(input.activity ? { activityId: MECH_LAB_ACTIVITY_ID, scenarioId: SCENARIO_ID } : {}),
    metadata: input.metadata ?? {},
  };
}

const eventRule = (
  knowledgePointIds: string[] = [],
  exerciseIds: string[] = [],
): SceneCompletionRule => ({
  type: 'learning_event',
  eventType: 'COMPLETE_SCENE',
  knowledgePointIds,
  exerciseIds,
});

export const SCENE_DEFINITIONS: readonly SceneDefinition[] = [
  scene({
    id: 'S01-01',
    stationId: 'station-01-system',
    title: '抢修任务导入',
    description: '进入“抢修停摆的自动生产线”工程任务背景。',
    sceneType: 'briefing',
    reuseStrategy: 'ENHANCE_EXISTING',
    capabilities: ['pbl'],
    learningMode: 'knowledge',
    completionRule: eventRule(),
    componentKey: 'pbl-project-shell',
    metadata: { projectStage: '识系统' },
  }),
  scene({
    id: 'S01-02',
    stationId: 'station-01-system',
    title: '3D设备探索',
    description: '识别自动生产线关键设备及其输入输出。',
    sceneType: 'exploration',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'visualization3d'],
    learningMode: 'knowledge',
    prerequisite: 'S01-01',
    completionRule: eventRule(['K01'], ['M01']),
    componentKey: 'system-learning-station',
    interactiveTemplate: 'line-stop-001-learning',
    activity: true,
  }),
  scene({
    id: 'S01-03',
    stationId: 'station-01-system',
    title: '感知—控制—执行分类',
    description: '将关键设备归入三层系统结构。',
    sceneType: 'classification',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'visualization3d'],
    learningMode: 'practice',
    prerequisite: 'S01-02',
    completionRule: eventRule(['K02']),
    componentKey: 'system-learning-station',
    activity: true,
  }),
  scene({
    id: 'S01-04',
    stationId: 'station-01-system',
    title: '物理流、信息流与控制流',
    description: '观察三种流在正常生产循环中的协同。',
    sceneType: 'simulation',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'visualization3d', 'simulation'],
    learningMode: 'practice',
    prerequisite: 'S01-03',
    completionRule: eventRule(['K03'], ['M02']),
    componentKey: 'system-learning-station',
    activity: true,
  }),

  scene({
    id: 'S02-01',
    stationId: 'station-02-sensing',
    title: '光电传感器原理',
    description: '拖动工件观察S2检测状态。',
    sceneType: 'simulation',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'simulation'],
    learningMode: 'knowledge',
    prerequisite: 'S01-04',
    completionRule: eventRule(['K04']),
    componentKey: 'sensing-learning-station',
    interactiveTemplate: 'sensing-station',
  }),
  scene({
    id: 'S02-02',
    stationId: 'station-02-sensing',
    title: '位置—信号预测',
    description: '先预测工件位置对应的信号，再验证。',
    sceneType: 'simulation',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'simulation'],
    learningMode: 'practice',
    prerequisite: 'S02-01',
    completionRule: eventRule(['K05'], ['M03']),
    componentKey: 'sensing-learning-station',
    interactiveTemplate: 'sensing-station',
  }),
  scene({
    id: 'S02-03',
    stationId: 'station-02-sensing',
    title: '24V与输出体检',
    description: '区分传感器供电状态与输出状态。',
    sceneType: 'measurement',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'simulation'],
    learningMode: 'practice',
    prerequisite: 'S02-02',
    completionRule: eventRule(['K06', 'K07'], ['M04', 'M05']),
    remediationFor: ['POWER_EQUALS_SENSOR_NORMAL'],
    componentKey: 'sensing-learning-station',
    interactiveTemplate: 'sensing-station',
  }),
  scene({
    id: 'S02-04',
    stationId: 'station-02-sensing',
    title: 'S2到I0.2映射',
    description: '双向追踪现场传感器与PLC输入地址。',
    sceneType: 'mapping',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'diagram', 'simulation'],
    learningMode: 'knowledge',
    prerequisite: 'S02-03',
    completionRule: eventRule(['K08']),
    componentKey: 'sensing-learning-station',
    interactiveTemplate: 'sensing-station',
  }),

  scene({
    id: 'S03-01',
    stationId: 'station-03-control',
    title: 'PLC输入与输出',
    description: '区分进入PLC的I信号与PLC发出的Q信号。',
    sceneType: 'exploration',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'diagram'],
    learningMode: 'knowledge',
    prerequisite: 'S02-04',
    completionRule: eventRule(['K09']),
    remediationFor: ['INPUT_OUTPUT_CONFUSION'],
    componentKey: 'control-learning-station',
    interactiveTemplate: 'control-station',
  }),
  scene({
    id: 'S03-02',
    stationId: 'station-03-control',
    title: '现场设备与地址匹配',
    description: '完成S2、推料控制与PLC地址的映射。',
    sceneType: 'mapping',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'diagram'],
    learningMode: 'practice',
    prerequisite: 'S03-01',
    completionRule: eventRule(['K10'], ['M06']),
    remediationFor: ['FIELD_IO_MAPPING_ERROR'],
    componentKey: 'control-learning-station',
    interactiveTemplate: 'control-station',
  }),
  scene({
    id: 'S03-03',
    stationId: 'station-03-control',
    title: 'PLC三步扫描',
    description: '依次读取输入、执行逻辑并更新输出。',
    sceneType: 'simulation',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'simulation'],
    learningMode: 'practice',
    prerequisite: 'S03-02',
    completionRule: eventRule(['K11']),
    remediationFor: ['PLC_SCAN_SEQUENCE_ERROR'],
    componentKey: 'control-learning-station',
    interactiveTemplate: 'control-station',
  }),
  scene({
    id: 'S03-04',
    stationId: 'station-03-control',
    title: '动态梯形图信号流',
    description: '根据I0.2触点状态推演Q0.1输出。',
    sceneType: 'simulation',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'diagram', 'simulation'],
    learningMode: 'practice',
    prerequisite: 'S03-03',
    completionRule: eventRule(['K12'], ['M07']),
    remediationFor: ['LADDER_LOGIC_CONFUSION'],
    componentKey: 'control-learning-station',
    interactiveTemplate: 'control-station',
  }),

  scene({
    id: 'S04-01',
    stationId: 'station-04-actuation',
    title: 'PLC输出到气缸执行链',
    description: '沿Q0.1、电磁阀、气路和气缸理解能量转换。',
    sceneType: 'exploration',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'visualization3d', 'diagram'],
    learningMode: 'knowledge',
    prerequisite: 'S03-04',
    completionRule: eventRule(['K13']),
    componentKey: 'actuation-learning-station',
    interactiveTemplate: 'actuation-station',
  }),
  scene({
    id: 'S04-02',
    stationId: 'station-04-actuation',
    title: 'Q0.1动态推演',
    description: '手动切换控制输出并观察气缸动作。',
    sceneType: 'simulation',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'visualization3d', 'simulation'],
    learningMode: 'practice',
    prerequisite: 'S04-01',
    completionRule: eventRule(['K13']),
    componentKey: 'actuation-learning-station',
    interactiveTemplate: 'actuation-station',
  }),
  scene({
    id: 'S04-03',
    stationId: 'station-04-actuation',
    title: '有输出不等于有动作',
    description: '比较Q0.1 ON与现场执行状态。',
    sceneType: 'diagnosis',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'visualization3d', 'simulation'],
    learningMode: 'diagnosis',
    prerequisite: 'S04-02',
    completionRule: eventRule(['K14']),
    remediationFor: ['CONTROL_EXECUTION_CONFUSION', 'OUTPUT_EQUALS_ACTUATION_SUCCESS'],
    componentKey: 'actuation-learning-station',
    interactiveTemplate: 'actuation-station',
  }),

  scene({
    id: 'S05-01',
    stationId: 'station-05-diagnosis',
    title: '察—查—测—断—验',
    description: '建立统一的循证诊断方法。',
    sceneType: 'briefing',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['diagram'],
    learningMode: 'diagnosis',
    prerequisite: 'S04-03',
    completionRule: eventRule(['K15']),
    componentKey: 'diagnosis-learning-station',
  }),
  scene({
    id: 'S05-02',
    stationId: 'station-05-diagnosis',
    title: '感知层诊断',
    description: '根据工件到位而I0.2 OFF判断信号链。',
    sceneType: 'diagnosis',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'diagram', 'simulation'],
    learningMode: 'diagnosis',
    prerequisite: 'S05-01',
    completionRule: eventRule(['K15'], ['M08-sensing']),
    remediationFor: ['SENSING_LAYER_CONFUSION'],
    componentKey: 'diagnosis-learning-station',
  }),
  scene({
    id: 'S05-03',
    stationId: 'station-05-diagnosis',
    title: '控制层诊断',
    description: '根据I0.2 ON而Q0.1 OFF判断控制链。',
    sceneType: 'diagnosis',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'diagram', 'simulation'],
    learningMode: 'diagnosis',
    prerequisite: 'S05-02',
    completionRule: eventRule(['K15'], ['M08-control']),
    remediationFor: ['CONTROL_LAYER_CONFUSION'],
    componentKey: 'diagnosis-learning-station',
  }),
  scene({
    id: 'S05-04',
    stationId: 'station-05-diagnosis',
    title: '执行层诊断',
    description: '根据Q0.1 ON而气缸不动判断执行链。',
    sceneType: 'diagnosis',
    reuseStrategy: 'REUSE_WITH_WRAPPER',
    capabilities: ['interactive_html', 'diagram', 'simulation'],
    learningMode: 'diagnosis',
    prerequisite: 'S05-03',
    completionRule: eventRule(['K15'], ['M08-actuation']),
    remediationFor: ['ACTUATION_LAYER_CONFUSION', 'EVIDENCE_SELECTION_ERROR'],
    componentKey: 'diagnosis-learning-station',
  }),

  scene({
    id: 'S06-01',
    stationId: 'station-06-virtual-lab',
    title: '综合抢修任务导入',
    description: '将前五站知识汇入自动生产线抢修任务。',
    sceneType: 'briefing',
    reuseStrategy: 'ENHANCE_EXISTING',
    capabilities: ['pbl', 'virtual_lab'],
    learningMode: 'diagnosis',
    prerequisite: 'S05-04',
    completionRule: eventRule(),
    componentKey: 'pbl-project-shell',
    activity: true,
    metadata: { projectStage: '战故障' },
  }),
  scene({
    id: 'S06-02',
    stationId: 'station-06-virtual-lab',
    title: '自动输送系统故障诊断',
    description: '运行现有line-stop-001旗舰Virtual Lab。',
    sceneType: 'virtual_lab',
    reuseStrategy: 'REUSE_DIRECT',
    capabilities: ['interactive_html', 'visualization3d', 'virtual_lab'],
    learningMode: 'diagnosis',
    prerequisite: 'S06-01',
    completionRule: { type: 'virtual_lab_assessment' },
    componentKey: 'virtual-lab-runner',
    interactiveTemplate: 'line-stop-001',
    activity: true,
  }),
  scene({
    id: 'S06-03',
    stationId: 'station-06-virtual-lab',
    title: '诊断路径评价入口',
    description: '复用现有Assessment结果与诊断时间线。',
    sceneType: 'assessment',
    reuseStrategy: 'REUSE_DIRECT',
    capabilities: ['assessment', 'analytics'],
    learningMode: 'assessment',
    prerequisite: 'S06-02',
    completionRule: { type: 'virtual_lab_assessment' },
    componentKey: 'virtual-lab-assessment',
    activity: true,
  }),

  scene({
    id: 'S07-01',
    stationId: 'station-07-assessment',
    title: '六维能力画像',
    description: '查看课件级六维确定性能力画像。',
    sceneType: 'assessment',
    reuseStrategy: 'REUSE_DIRECT',
    capabilities: ['assessment', 'analytics'],
    learningMode: 'assessment',
    prerequisite: 'S06-03',
    completionRule: { type: 'station_profile' },
    componentKey: 'assessment-learning-station',
  }),
  scene({
    id: 'S07-02',
    stationId: 'station-07-assessment',
    title: '精准补救',
    description: '根据概念误区和薄弱能力返回既有学习站。',
    sceneType: 'remediation',
    reuseStrategy: 'REUSE_DIRECT',
    capabilities: ['assessment', 'analytics'],
    learningMode: 'assessment',
    prerequisite: 'S07-01',
    completionRule: { type: 'station_profile' },
    componentKey: 'assessment-learning-station',
  }),
  scene({
    id: 'S07-03',
    stationId: 'station-07-assessment',
    title: '再练与教师学情',
    description: '复用再练比较和教师课件级学情分析。',
    sceneType: 'assessment',
    reuseStrategy: 'REUSE_DIRECT',
    capabilities: ['assessment', 'analytics'],
    learningMode: 'assessment',
    prerequisite: 'S07-02',
    completionRule: { type: 'station_profile' },
    componentKey: 'assessment-learning-station',
  }),
] as const;

export const SCENE_DEFINITION_BY_ID = new Map(
  SCENE_DEFINITIONS.map((definition) => [definition.id, definition]),
);
